# Site
title:               MBT Bundle
tagline:             A Model Based Testing tool
description:         MBT Bundle is an open-source tool that allow you to test your application using Model Based Testing technique

# About/contact
author: # you can edit these to be your personal details
  name:              Tien Vo
  url:               https://tienvx.github.io/
  email:             tien.xuan.vo@gmail.com
  title:             PHP Developer

# Social
github_username: tienvx
twitter_username: tienvoxuan
facebook_username: tien.voxuan
linkedin_username: tienxuanvo
pinterest_username: tienxuanvo

widgets:
  - title: About
    url: about
    archor: true
  - title: Screenshots
    url: screenshots
    archor: true
  - title: Docs
    url: docs
    archor: true
  - title: License
    url: license
    archor: true
  - title: Contact
    url: contact
    archor: true
