name: main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy
      run: GIT_USER=tienvx USE_SSH=1 yarn deploy
