name: main

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install
      run: yarn install

    - name: Deploy
      run: |
        cat <<- EOF > $HOME/.netrc
          machine github.com
          login $GIT_USER
          password $ACCESS_TOKEN

          machine api.github.com
          login $GIT_USER
          password $ACCESS_TOKEN
        EOF
        chmod 600 $HOME/.netrc

        git config --global user.name $GIT_USER
        git config --global user.email $GIT_USER@users.noreply.github.com
        yarn deploy
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GIT_USER: ${{ secrets.GIT_USER }}
